export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

export const REMOVE_TODO = 'REMOVE_TODO';

export const CHANGE_TODO_REQUEST = 'CHANGE_TODO_REQUEST';
export const CHANGE_TODO_SUCCESS = 'CHANGE_TODO_SUCCESS';
export const CHANGE_TODO_FAILURE = 'CHANGE_TODO_FAILURE';

export const GET_TODOS_REQUEST = 'GET_TODOS_REQUEST';
export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';

export const GET_TODOLOGS_REQUEST = 'GET_TODOLOGS_REQUEST';
export const GET_TODOLOGS_SUCCESS = 'GET_TODOLOGS_SUCCESS';
export const GET_TODOLOGS_FAILURE = 'GET_TODOLOGS_FAILURE';